### ISSUE TITLE
Feature Request: Map Layer with dynamic coloring

### ISSUE THREAD

**Issue by pka** [HusseinKabbout/minimap#1]
I would like to have an additional layer (GeoJSON for now) as in http://doc.qt.io/qt-5/location-plugin-mapboxgl.html#example-usage. This should put a blue line on the map.

Next step would be adding a GUI element (e.g. a radio button), which switches the line color. This should be possible by changing the `lineColor` property of the `paint` MapParameter.

**Comment by HusseinKabbout** [comment]
I have implemented your request.
